services:
  olmocr-worker:
    image: alleninstituteforai/olmocr:latest
    container_name: olmocr-worker
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: ${GPU_COUNT}
              device_ids: ["${GPU_DEVICE_ID}"]
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=${GPU_DEVICE_ID}
      - GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION}
      - MAX_MODEL_LEN=${MAX_MODEL_LEN}
      - TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE}
      - DATA_PARALLEL_SIZE=${DATA_PARALLEL_SIZE}
      - PORT=${PORT}
      - HF_HOME=/hf_cache
      - WORKSPACE_DIR=${WORKSPACE_DIR}
      - INPUT_PDF_DIR=${INPUT_PDF_DIR}
      - PAGES_PER_GROUP=${PAGES_PER_GROUP}
      - MAX_PAGE_RETRIES=${MAX_PAGE_RETRIES}
      - MAX_PAGE_ERROR_RATE=${MAX_PAGE_ERROR_RATE}
      - WORKERS=${WORKERS}
      - TARGET_LONGEST_IMAGE_DIM=${TARGET_LONGEST_IMAGE_DIM}
      - TARGET_ANCHOR_TEXT_LEN=${TARGET_ANCHOR_TEXT_LEN}
    volumes:
      - ${WORKSPACE_DIR}:/local_files
      - ${WORKSPACE_DIR}/hf_cache:/hf_cache
    command: >
      sh -c "while true; do
        python -m olmocr.pipeline $${WORKSPACE_DIR} --markdown --pdfs \"$${INPUT_PDF_DIR}\" --gpu-memory-utilization $${GPU_MEMORY_UTILIZATION} --max_model_len $${MAX_MODEL_LEN} --tensor-parallel-size $${TENSOR_PARALLEL_SIZE} --data-parallel-size $${DATA_PARALLEL_SIZE} --port $${PORT} --pages_per_group $${PAGES_PER_GROUP} --max_page_retries $${MAX_PAGE_RETRIES} --max_page_error_rate $${MAX_PAGE_ERROR_RATE} --workers $${WORKERS} --target_longest_image_dim $${TARGET_LONGEST_IMAGE_DIM} --target_anchor_text_len $${TARGET_ANCHOR_TEXT_LEN};
        sleep 10;
      done"
    restart: unless-stopped

  olmocr-app:
    container_name: olmocr-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${STREAMLIT_PORT}:8501"
    volumes:
      - ${WORKSPACE_DIR}:/local_files
      - ./streamlit_app.py:/app/streamlit_app.py
    depends_on:
      - olmocr-worker
    environment:
      - WORKSPACE_DIR=${WORKSPACE_DIR}
      - INPUT_PDF_DIR=${INPUT_PDF_DIR}
      - OUTPUT_MARKDOWN_DIR=${OUTPUT_MARKDOWN_DIR}
    restart: unless-stopped
