services:
  olmocr-streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: olmocr-streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ./workspace:/workspace
      - .:/app
    environment:
      - PYTHONPATH=/app
      - VLLM_BASE_URL=http://vllm-server:8000
    depends_on:
      vllm-server:
        condition: service_healthy
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0

volumes:
  vllm_cache:
    driver: local
